project:
  type: website

website:
  title: "#30daychartchallenge 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true


execute:
  _freeze: auto
  
  