---
title: "Day 17: Birds"
format: html
execute:
  eval: true
  echo: false
  message: false
  warning: false
---

```{r}
library(tidyverse)
library(tidyplots)
library(ggridges)
```

# Exploring penguins' mass distribution
```{r}
#| echo: true
library(palmerpenguins)

```

## Classig ggplot /w faceting 
```{r}
#| echo: true
#| label: "classic"

penguins |> 
  mutate(island = fct_rev(island)) |>
  ggplot(aes(x=body_mass_g)) +
  geom_density(aes(color = species, fill=species), alpha=0.25, size=1) +
  # change order of facets
  facet_wrap(~island, nrow=3) +
  scale_color_brewer(palette = "Set1") + scale_fill_brewer(palette = "Set1") +
  scale_y_continuous(labels = NULL, breaks = NULL) + ylab(NULL) +
  theme(
    legend.position = c(1, 1), 
    legend.justification = c(1, 1), 
    legend.direction = "horizontal", 
    legend.title = element_blank(), 
    legend.background = element_rect(fill="lightgrey"))
```

## Using ggridges

```{r}
#| echo: true
#| label: "ridgelines"

penguins |> 
  ggplot(aes(x=body_mass_g, y=island)) +
  geom_density_ridges(aes(color = species, fill=species), alpha=0.5, size=1) +
  theme_ridges() +
  # position legend inside the plot in right upper corner
  theme(legend.position = c(1, 1), legend.justification = c(1, 1), legend.direction = "horizontal", legend.title = element_blank())
```

## Bonus: Using tidyplots
```{r}
#| echo: true
#| label: "tidyplot"

penguins |> tidyplot(y=island,  x = body_mass_g, fill=species) |> add_violin() |> add_data_points_beeswarm()

```
