---
title: "Day5: Rankings"
format: html
execute:
  eval: true
  echo: false
  message: false
  warning: false
---

```{r}
library(tidyverse)
library(pixarfilms)
library(ggtext)
```

```{r}

all_data <- pixar_films |> left_join(public_response) |> left_join(box_office)

cars2 <- all_data |> filter(film == "Cars 2") 
top_rated <- all_data |> filter(!is.na(film) & !is.na(metacritic)) |>  arrange(desc(metacritic)) |> head(10)
df <-  bind_rows(top_rated, cars2)

```



```{r}
df |> 
  ggplot(aes(metacritic, fct_reorder(film, metacritic))) + 
  geom_point(size = 4, color= "#FF9149") +
  geom_segment(aes(yend=film), xend=0, color="#FF9149", linewidth = 3) +
  geom_label(aes(label=metacritic), hjust=0, nudge_x=0.4, fill = "#AFDDFF", color = "#FF9149") +
  labs(
    title = "Pixar films with the highest Metacritic scores",
    subtitle = "And then there's Cars 2...",
    x = "Metacritic score",
    y = NULL
  ) +

  scale_x_continuous(breaks = NULL) +
  theme_void() +
  theme(
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank(),
    plot.background = element_rect(fill = "#60B5FF", color = "#60B5FF"),
    panel.background = element_rect(fill = "#60B5FF", color = "#60B5FF"),
    axis.text.y = element_text(family = "Ubuntu", color = "#FFECDB", size = 16),
    plot.title = element_textbox(family = "Ubuntu", color = "#FFECDB", size = 18, hjust = 0.5),
    plot.subtitle = element_textbox(family = "Ubuntu", color = "#FFECDB", size = 12, hjust = 0.5),
  )


```